// RFC 6962 Merkle tree: leaf = SHA-256(0x00 || data), node = SHA-256(0x01 || l || r).
// Small, recursive, no dependencies. Log sizes here are thousands, not billions;
// clarity beats cleverness.

import { createHash } from 'node:crypto';

function sha(...bufs) {
  const h = createHash('sha256');
  for (const b of bufs) h.update(b);
  return h.digest();
}

export function leafHash(data) {
  return sha(Buffer.from([0]), data);
}

export function nodeHash(left, right) {
  return sha(Buffer.from([1]), left, right);
}

// Largest power of two strictly less than n (RFC 6962 split point).
function splitPoint(n) {
  let k = 1;
  while (k * 2 < n) k *= 2;
  return k;
}

/** Root over an array of leaf-hash Buffers. */
export function rootOf(leaves) {
  const n = leaves.length;
  if (n === 0) return sha(Buffer.alloc(0)); // empty-tree hash, RFC 6962
  if (n === 1) return leaves[0];
  const k = splitPoint(n);
  return nodeHash(rootOf(leaves.slice(0, k)), rootOf(leaves.slice(k)));
}

/**
 * Inclusion proof for leaves[index]: array of { hash, side } where side is
 * which side the SIBLING sits on ('left' | 'right') when recombining upward.
 */
export function inclusionProof(index, leaves) {
  const n = leaves.length;
  if (n === 1) return [];
  const k = splitPoint(n);
  if (index < k) {
    return [...inclusionProof(index, leaves.slice(0, k)), { hash: rootOf(leaves.slice(k)), side: 'right' }];
  }
  return [...inclusionProof(index - k, leaves.slice(k)), { hash: rootOf(leaves.slice(0, k)), side: 'left' }];
}

/**
 * The side each sibling MUST sit on, derived from (index, size) alone, in the
 * same bottom-up order inclusionProof emits.
 *
 * This exists because trusting the `side` values carried in the proof makes
 * the claimed leaf index decorative: a receipt's index could be changed and
 * the walk would still reach the same root, so a holder could misstate their
 * position in the log while the receipt still "verified". Position is part of
 * what the log claims to establish (chronology between registrations), so it
 * has to be bound. Deriving the sides here makes the index load-bearing, and
 * is what RFC 6962 verification does anyway. Honestly issued proofs are
 * unaffected: they are generated by the same construction.
 */
export function expectedSides(index, size) {
  const sides = [];
  let i = index;
  let n = size;
  while (n > 1) {
    const k = splitPoint(n);
    if (i < k) {
      sides.push('right'); // sibling is the right subtree
      n = k;
    } else {
      sides.push('left'); // sibling is the left subtree
      i -= k;
      n -= k;
    }
  }
  return sides.reverse();
}

/** Verify an inclusion proof. All hashes are Buffers except proof entries may carry hex strings. */
export function verifyInclusion(leaf, index, size, proof, root) {
  if (!Number.isInteger(index) || !Number.isInteger(size)) return false;
  if (index < 0 || index >= size) return false;

  const sides = expectedSides(index, size);
  if (proof.length !== sides.length) return false;

  let current = Buffer.isBuffer(leaf) ? leaf : Buffer.from(leaf, 'hex');
  for (let step = 0; step < proof.length; step += 1) {
    if (proof[step].side !== sides[step]) return false;
    const sibling = Buffer.isBuffer(proof[step].hash) ? proof[step].hash : Buffer.from(proof[step].hash, 'hex');
    if (sides[step] === 'right') current = nodeHash(current, sibling);
    else current = nodeHash(sibling, current);
  }
  const expected = Buffer.isBuffer(root) ? root : Buffer.from(root, 'hex');
  return current.equals(expected);
}
